config/routes.rb
Rails.application.routes.draw do
  resources :funnies

  devise_for :users
  root "funnies#index"
  get "about" => "pages#about"
  get "contactus" => "pages#contactus"
  get "funnies" => "pages#funnies"

end

app/models/funny.rb
class Funny < ActiveRecord::Base
	belongs_to :user
	
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
		# :storage => :s3, 
		# :bucket => 'finallyfunny', 
		# :s3_credentials => S3_CREDENTIALS
		# :storage => :s3, 
		# :bucket => ENV['finallyfunny']
	# validates :image, presence: true 
	# validates :description, presence: true	
	do_not_validate_attachment_file_type :image 
		

	validates :image, presence: true
	validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :funnies      

  validates :name, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

   def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/funnies_controller.rb
# require 'pry'
class FunniesController < ApplicationController
  before_action :set_funny, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # above you can edit what you would like to see or NOT see
  # if a person is signed in or not 

  # GET /funnies
  # GET /funnies.json
  def index
    @funnies = Funny.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 10) # .all gives you all of them in which they were created 
  end

  # GET /funnies/1
  # GET /funnies/1.json
  def show
  end

  # GET /funnies/new
  def new
    @funny = current_user.funnies.build
  end # this is another way to create a funny

  # GET /funnies/1/edit
  def edit
  end

  # POST /funnies
  # POST /funnies.json
  def create
    @funny = current_user.funnies.build(funny_params)

    respond_to do |format|
      if @funny.save
        format.html { redirect_to @funny, notice: 'Funny was successfully created.' }
        format.json { render :show, status: :created, location: @funny }
      else
        format.html { render :new }
        format.json { render json: @funny.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funnies/1
  # PATCH/PUT /funnies/1.json
  def update
    respond_to do |format|
      if @funny.update(funny_params)
        format.html { redirect_to @funny, notice: 'Funny was successfully updated.' }
        format.json { render :show, status: :ok, location: @funny }
      else
        format.html { render :edit }
        format.json { render json: @funny.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funnies/1
  # DELETE /funnies/1.json
  def destroy
    @funny.destroy
    respond_to do |format|
      format.html { redirect_to funnies_url, notice: 'Funny was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funny
      @funny = Funny.find(params[:id])
    end

    def correct_user
      # binding.pry
      # check if the user's signed in 
      # if current_user && current_user.funny_ids.include?(params[:id])
      if current_user && current_user.funny_ids.include?(params[:id])
      # @funny = current_user.funnies.find_by(id: params[:id])
        redirect_to funnies_path, notice: "Not authorized to edit this pin" if @funny.nil?
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funny_params
      params.require(:funny).permit(:description, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contactus
  end

  def funnies
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/funnies_helper.rb
module FunniesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/funnies/_form.html.erb
<%= form_for @funny, html: {multipart: true} do |f| %>
  <% if @funny.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@funny.errors.count, "error") %> prohibited this funny from being saved:</h2>

      <ul>
      <% @funny.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/funnies/edit.html.erb
<h1>Editing funny</h1>

<%= render 'form' %>

<%= link_to 'Show', @funny %> |
<%= link_to 'Back', funnies_path %>

app/views/funnies/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="funnies" class="transitions-enabled">
  <% @funnies.each do |funny| %><!-- will do something to each funny -->
    <div class="box panel panel-default">
      <%= link_to image_tag(funny.image.url(:medium)), funny %>
      <div class="panel-body">
        <p><%= funny.description %></p>
        <p><strong><%= funny.user.name if funny.user %></strong></p><!-- only will show if a funny has a user -->
        <% if funny.user == current_user %>
          <div class="actions">
            <%= link_to edit_funny_path(funny) do %>
              <span class="glyphicon glyphicon-edit"></span>
              edit
            <% end %>
            <%= link_to funny, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              delete
            <% end %>
          </div>  
        <% end %> 
      </div>
    </div>   
  <% end %>
</div>

<div class="center">
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/funnies/new.html.erb
<h1>New funny</h1>

<%= render 'form' %>

<%= link_to 'Back', funnies_path %>

app/views/funnies/show.html.erb
<%= link_to 'Back', funnies_path %>

<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading center">
				<%= image_tag @funny.image.url(:medium) %>
			</div>	
			
			<div class="panel-body">
				<p><%= @funny.description %></p>
				<p><strong><%= @funny.user.name if @funny.user %></strong></p>

				<% if @funny.user == current_user %>
					<%= link_to edit_funny_path(@funny) do %>
            <span class="glyphicon glyphicon-edit"></span>
              edit
          <% end %>
				<% end %>
			</div>	
		</div>
	</div>		
</div>		

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Finally Funny", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "home", root_path %></li>
        <li><%= link_to "funnies", funnies_path %></li>
        <li><%= link_to "about", about_path %></li>
        <li><%= link_to "contact", contactus_path %></li>
        <% if user_signed_in? %>
          <li>
            <%= link_to new_funny_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Pin
            <% end %>
          </li>
          <li><%= link_to "account settings", edit_user_registration_path %></li>
          <li><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
  </nav>

<!-- This document is linked by our other pages referring to it with erb -->  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Finally Funny</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	<%= render 'layouts/header' %>
		
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>

</body>
<footer>
	<p>Finally Funny Made in NYC</p>
</footer>

</html>

app/views/pages/_home.html.erb
<div class="jumbotron">	
	<h1>Finally Funny</h1>
	<p>When something really embarrassing happens to you it is not really funny at the moment. Then a few weeks go by and all of sudden you look back and think "that was funny!". Here you can share all your "finally funny" moments and get to read some from others.</p>	
		<p>
			<%= link_to "log in", new_user_session_path, class: "btn btn-default btn-lg" %>
			<%= link_to "sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
		</p>
</div>

app/views/pages/about.html.erb
<div class="jumbotron">
	<h1>About</h1>
	<p>Pol</p>
</div>	

<div class="jumbotron">
	<p>Here is an example of what the content will be like! There would be a lot of text here. There can be some photos here as well.</p>
</div>	

app/views/pages/contactus.html.erb
<div class="jumbotron">
	<h1>Comments</h1>
</div>

<div class="jumbotron center">
	<p>Let us know what you think! We would love to here from you!</p>
</div>

<div class="jumbotron">
	<form role="form" method="get">
		<div class="name">
	    <label for="name">First Name</label>
	    <br>
	    <input type="text" class="text" placeholder="first name">
	  </div>
	  <div class="name">
	    <label for="name">Last Name</label>
	    <br>
	    <input type="text" class="text" placeholder="last name">
	  </div>
	  <div class="form-group">
	    <label for="exampleInputEmail1">Email address</label>
	    <br>
	    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
	  </div>
	  <div class="comment">
	    <label for="comment">Comments</label>
	    <br>
	    <textarea id="message" name="message" placeholder="comment..." required="required"></textarea>
	  </div>
	  <br>
	  <button type="submit" class="btn btn-default">Submit</button>
	</form>
</div>	

app/views/pages/funnies.html.erb
<div class="jumbotron">
	<h1>Funnies</h1>
	<p>post your funny moments</p> 
</div>	